package org.example.util;

import org.example.dao.ProductDAOImpl;
import org.example.model.Product;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.List;
import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;

public class CSVHelper {
    private static final String REPORT_DIR = "reports";

    public static String generateProductsReport(List<Product> products, String generatedBy) {
        try {
            File dir = new File(REPORT_DIR);
            if (!dir.exists()) {
                dir.mkdirs();
            }

            String fileName = REPORT_DIR + "/inventory_report_" +
                    new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".csv";

            try (PrintWriter writer = new PrintWriter(new FileWriter(fileName))) {
                writer.println("=== Inventory Report ===");
                writer.println("Generated By: " + generatedBy);
                writer.println("Generated On: " +
                        new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
                writer.println();
                writer.println("ID,Name,Category,Quantity,Price");
                writer.println();
                if (products != null && !products.isEmpty()) {
                    for (Product p : products) {
                        writer.println(p.getId() + "," +
                                p.getName() + "," +
                                p.getCategory() + "," +
                                p.getQuantity() + "," +
                                p.getPrice());
                    }
                } else {
                    writer.println("No products available.");
                }
                writer.println();
                writer.println("Total Products: " + (products != null ? products.size() : 0));
                System.out.println("✔ Report saved successfully: " + fileName);

                return fileName;
            }
        } catch (IOException e) {
            System.out.println("✘ Error writing report: " + e.getMessage());
            return null;
        }
    }
}

